# Scenario metadata - tracks run statistics
scenarioId: demo-logout-001
slug: logout-flow
createdAt: "2025-12-07T00:00:00Z"
lastRunAt: null
totalRuns: 0
passCount: 0
failCount: 0
avgDuration: null
lastStatus: never_run
